### ISSUE TITLE
add custom classes to different series?

### ISSUE THREAD

**Issue by Syndesi** [tmmdata/chartist-plugin-tooltip#119]
Hi,

is it possible to add classes to different series so that e.g. the tooltip has the same color as the serie?

Have a nice day,
Syndesi

**Comment by jezmck** [comment]
Yes, each `series` can have a `className` property.

**Comment by danielpost** [comment]
For anyone looking to do this, here's how I managed to do this for a line chart (in JavaScript):

```js
chart.on('created', () => {
    const points = document.querySelectorAll('.ct-point');
    const tooltip = document.querySelector('chartist-tooltip');

    points.forEach(point => {
        point.addEventListener('mouseover', () => {
            tooltip.className = 'chartist-tooltip';
            tooltip.classList.add(point.parentElement.classList[1]);
        });
    });
});
```

Essentially all this does is add the class of the series to the tooltip every time you hover over a point. You can then use this to style the tooltip, for example:

```css
.chartist-tooltip.ct-series-a { background-color: red; }
.chartist-tooltip.ct-series-b { background-color: blue; }
```
